- src/App.css
- src/components/CurrentWeather.css
- src/components/CurrentWeather.jsx
- src/components/ErrorBoundary.jsx
- src/components/ExpectedWeather.css
- src/components/ExpectedWeather.jsx
- src/components/SearchBar.css
- src/components/SearchBar.jsx
- src/components/Weather.jsx
- src/index.css
- src/pages/LandingSearch.css
- src/pages/LandingSearch.jsx
- src/pages/WeatherDisplay.jsx
- src/services/api.js
- Added intergration with https://openweathermap.org/
- The main intergration is performed in services/api.js
- Functions added to CurrentWeather and ExpectedWeather components
- Weather components now uses props with the data retrieved
- Learnt and used useState and useEffect for first time, not in the React fundermentals course I completed.
- Had issue where nothing was loading
> Consider adding an error boundary to your tree to customize error handling behavior. Visit https://react.dev/link/error-boundaries to learn more about error boundaries.
- Added ErrorBoundary component.
- Wraped ErrorBoundary around Weather in the CurrentWeather and ExpectedWeather components return.
- Applied formating changes to all files where defaut indentation was 4 spaces. This was my fault 🤦‍♂️ 
- Noticed …
> Added API Intergration. Added ErrorBoundary. Fixed inconsistent code.

- .env
- src/components/CurrentWeather.jsx
- src/components/ExpectedWeather.jsx
- src/components/SearchBar.css
- src/components/SearchBar.jsx
- src/components/Weather.jsx
- src/hooks/useWeather.js
- src/pages/WeatherDisplay.jsx
This PR addresses these key issues from your comments: 
1. Repeated logic for fetching data in multiple components
2. API logic location for best practices
3. Light DRY violations 😄 
4. Search bar not hooked to actual location
Implemented a suggestions dropdown under the search input.
Suggests matching UK cities from a static list (["London", "Leeds", "Liverpool", "Manchester", "Birmingham", "Bristol"]) as the user types.
Displays top 3 matches dynamically.
Clicking a suggestion triggers navigation and initiates the weather search.
Fixed a weatherData is not defined error in ExpectedWeather.jsx by using the correct destructured variable.
Removed unnecessary use of key as a prop inside the Weather component, resolving the React warning.
Minor refactorings for clarity and code cleanliness. …
> Search bar functionality, API hook fix

- src/App.css
- src/App.jsx
- src/components/BrollyWeather.css
- src/components/BrollyWeather.jsx
- src/components/CurrentWeather.css
- src/components/CurrentWeather.jsx
- src/components/ExpectedWeather.css
- src/components/ExpectedWeather.jsx
- src/components/Weather.jsx
- src/pages/WeatherDisplay.css
- src/pages/WeatherDisplay.jsx
(drum roll)
Added some long overdue love to this page, bringing it visually (almost) in line with the amazing Figma mockup you put together for us.
* **WeatherDisplay**, **CurrentWeather** and **ExpectedWeather** components have all been restyle to match the design 
* Optional condition label removed where unnecessary ('Clear'/'Rainy' etc does not show on the mockups, but if you want it in the app, it's a simple fix to go back to it)
🗒️ make it mobile responsive
🗒️ switching to the logo of your choice (wasn't sure which one from the very many options you made is the winner haha) 
🗒️ adding some hover micro interactions just for fun 
I did not update any of the logic in this PR, as I know you have ambitious goals of figuring things out and experimenting. I wanna give you the opportunity to …
> styling: WeatherDisplay layout

- src/components/BrollyWeather.css
- src/components/BrollyWeather.jsx
- src/components/ExpectedWeather.jsx
- src/components/SearchBar.jsx
- src/hooks/useBrolly.js
- src/hooks/useLocation.js
**Brolly Advice and Message**
Implements a comprehensive set of advice and messages to inform users about the current weather conditions and provide guidance on whether or not they need an brolly.
**Brolly Expected Message**
Addresses a previously overlooked part of the issue where the weather message incorrectly indicated snow. This has been corrected to accurately reflect the actual weather conditions.
**UK Locations**
Restricts the application to exclusively serve weather data for UK locations by filtering results from the OpenWeatherMap API. This ensures more relevant and accurate information for our target users.
> feat: Brolly message | fix: Expected message | refactor: UK Locations

- src/components/BrollyWeather.jsx
- src/components/CurrentWeather.jsx
- src/components/ExpectedWeather.jsx
- src/hooks/useBrolly.js
- Reintroduced *"Yes/No"*, and added *"Maybe"* option in the BrollyWeather component.
- Refactored `useBrolly` hook to focus solely on message delivery, preparing for potential backend integration.
- Simplified the `nextBrolly` logic within the ExpectedWeather component.
> refactor: Changes to Expected and Brolly components

- src/components/BrollyWeather.jsx
- src/components/CurrentWeather.jsx
- src/components/ExpectedWeather.jsx
- src/components/SearchBar-API.jsx
- src/components/SearchBar.jsx
- src/hooks/useWeather.js
- src/pages/WeatherDisplay.jsx
**Summary:**
Improvements made to the location search functionality. It replaces the OpenWeatherMap Geocoding API with a local JSON file containing UK-only locations, implements fuzzy search for more flexible matching, ensures the OpenWeatherMap API uses only UK results, and resolves an inconsistency in the data used by different components.
**Changes Included:**
- **Use Local JSON for UK Locations:** The search functionality now utilizes the `uk_locations.min.json` file as the source of UK-specific location data. This provides a more comprehensive and maintainable list of potential search terms.
- **Implement Fuzzy Search:** The search logic has been enhanced to support fuzzy matching. This allows users to find locations by only typing a few letters, improving the user experience.
- …
> feat: Location search now powered by local json

- src/components/BrollyWeather.jsx
- src/components/CurrentWeather.jsx
- src/components/ExpectedWeather.jsx
- src/context/WeatherContext.jsx
- src/main.jsx
- src/pages/WeatherDisplay.jsx
This PR optimises weather data fetching using `useContext`, reducing API calls in `useWeather` from 8. It also eliminates prop drilling for weather and location data.
**Key Changes:**
- **Fewer Fetch Calls:** `useWeather` now fetches data once (twice in dev due to `StrictMode`).
- **No More Prop Drilling:** `useContext` shares weather and location data directly.
- **ErrorBoundary Removed (Temp):** Will be reintroduced later.
- **Improved ExpectedWeather:** Minor function improvements.
**Benefits:**
- Improved performance and cleaner code.
> fix: Reduced fetch requests by implementing useContext

- src/App.css
- src/components/Boundary.jsx
- src/components/BrollyWeather.jsx
- src/components/CurrentWeather.jsx
- src/components/ErrorBoundary.jsx
- src/components/ExpectedWeather.jsx
- src/components/Loading.css
- src/components/Loading.jsx
- src/components/LocationSection.jsx
- src/hooks/useWeather.js
- src/pages/LandingSearch.jsx
- src/pages/WeatherDisplay.jsx
**WeatherDisplay Loading States**
Added loading states for the `WeatherDisplay` page.
***Option 1:***
**Page-level loading** using a classic three-dot animation.
https://github.com/user-attachments/assets/dc79cb3d-b4d4-41da-aa94-4129cf9f1327
***Option 2:***
**Component-level loading** with a skeleton placeholder animation.
https://github.com/user-attachments/assets/6693e33f-6dd6-44ba-b85d-29ada591f9b3
- Loading behavior is currently set on component level for now, and could use further refinement. If Page level loading is prefered a small tweak to the code can change this.
- Loading is normally very quick, but can be simulated to last longer for testing using the `setTimeout` function in `useWeather`.
**Error Boundaries**
Reintroduced an error boundary wrapping the `WeatherDisplay` and …
> Loading and error handling

- src/App.css
- src/App.jsx
- src/components/LocationSection.jsx
- src/pages/NotFound.jsx
> feat: 404 Not Found

- src/components/Modal.css
- src/components/Modal.jsx
- src/pages/WeatherDisplay.jsx
This PR adds a new `Modal` component and integrates it into the `WeatherDisplay` page to enable a full-page search experience with suggestions.
- Opens the modal when the **Search** button on the `WeatherDisplay` page is clicked.
- Closes the modal when the **Close** button inside the modal is clicked.
- Supports rendering any child components within the modal.
- Enhances the user experience by allowing users to search for a new location directly from the `WeatherDisplay` page.
- Close the modal automatically when a location is selected.
- Improve the styling for the search interface.
> feat: Added modal component

- src/App.css
- src/components/SearchBar.jsx
- src/pages/LandingSearch.jsx
- src/pages/WeatherDisplay.jsx
- Search is now displayed within a full-page modal, ensuring results appear without disrupting other page elements or causing layout shifts.
- Refreshed styling for a cleaner, more consistent look across all themes.
- Search functionality has been fully integrated into the Weather page.
- Implement smooth animations for modal opening and closing transitions to enhance the user experience.
> feat: Added search into modal and gave it a new look

- src/App.jsx
- src/components/GeoLocation.jsx
- src/components/SearchBarGeo.jsx
- src/hooks/useGeoLocation.js
- src/hooks/useWeatherGeo.js
- src/pages/LandingSearch.jsx
- src/pages/WeatherDisplay.jsx
- src/pages/WeatherDisplayGeo.jsx
#**Implement Geolocation and Coordinate-Based Search**
This pull request introduces several key improvements to enhance the location handling within the weather application:
**Key Changes:**
* **Implemented Geolocation:** Integrated the `useGeoLocation` hook to fetch the user's current latitude and longitude.
* **Coordinate-Based Weather Fetching:** Modified the `useWeather` hook to primarily fetch weather data using latitude and longitude, ensuring more accurate results.
* **URL Parameter Handling:** Updated the application to read `lat` and `lon` parameters from the URL, allowing users to share specific weather locations. This overrides the automatic geolocation if coordinates are present in the URL.
* **SearchBar Integration:** The `SearchBar` component now navigates to the `/weather` …
> feat: Added use of Current Location

- src/components/SearchBarGeo.jsx
#**Optimize location JSON data and simplify SearchBarGeo**
This PR focuses on improving the efficiency and maintainability of the geographical search functionality by optimizing the underlying JSON data and simplifying the `SearchBarGeo` component.
**Key changes:**
- **Optimized JSON Data:** The JSON data file has been processed to remove unnecessary information, resulting in a reduction in file size from 13.8MB to 5.4MB. This will lead to faster data loading and reduced bandwidth consumption.
- **Simplified SearchBarGeo:** The component has been updated to work directly with the optimized data. This includes:
- Removal of logic that previously corrected incorrect latitude and longitude data.
- Elimination of the need to choose between `name_1` and `name_2` fields, as there is now a …
> feat: Optimize location JSON data and simplify SearchBarGeo

- package-lock.json
- package.json
- src/App.jsx
- src/components/ErrorBoundary.jsx
- src/components/Loading.jsx
- src/components/LocationGeo.jsx
- src/components/LocationSearch.jsx
- src/components/WeatherBrolly.jsx
- src/components/WeatherCurrent.jsx
- src/components/WeatherExpected.jsx
- src/hooks/useLocation.js
- src/hooks/useWeather.js
- src/main.jsx
- src/pages/Landing.jsx
- src/pages/Weather.jsx
Enhanced the application with `sonner` toasts for better user feedback on loading and errors:
* **ErrorBoundary Improvements:** Unhandled errors and 404s caught by the `ErrorBoundary` now trigger informative error toasts when redirecting to the landing page.
* **No Search Results:** Searches with no matches now display an "info" toast.
* **Geolocation Errors:** Denied geolocation access now shows a "error" toast.
* **API Errors:** Failed to fetch data from API now shows a "error" toast.
These changes provide clearer, immediate feedback to users during various application states and error scenarios.
> feat: Loading and Error handling improved with Toast

- src/components/LocationGeo.jsx
- src/components/LocationSearch.jsx
- src/components/WeatherBrolly.jsx
- src/data/brolly.json
- src/hooks/useBrolly.js
- src/hooks/useLocationGeo.js
- src/hooks/useLocationSearch.js
- **useBrolly now uses JSON:** Replaced the large static object previously in the hook with a local JSON file. This makes the logic cleaner and prepares the codebase for future migration to API-based data fetching.
- **useLocationSearch created:** Extracted the location data loading logic from the LocationSearch component into a reusable hook. This improves separation of concerns and keeps toast-based error handling in the component.
- **useLocation renamed to useLocationGeo:** Renamed for clarity and consistency now that useLocationSearch exists. This avoids confusion between general location search and geolocation logic.
> feat: useBrolly now uses JSON, useLocationSearch created

- src/components/WeatherCurrent.jsx
- src/components/WeatherExpected.jsx
- src/components/WeatherItem.jsx
- src/pages/Weather.css
- src/pages/Weather.jsx
Adds a UI toggle for switching between Celsius and Fahrenheit temperature displays.
**Implementation:**
- Implemented a toggle UI element.
- Dynamically converts displayed temperature values.
**Next Steps:**
- Save the user's temperature unit preference.
- Refactor current logic into a reusable component and hook.
> feat: change between celsius and fahrenheit with toggle

- src/App.css
- src/components/LocationGeo.css
- src/components/LocationSearch.css
- src/components/UnitToggle.css
- src/pages/Landing.css
- src/pages/Location.css
- src/pages/Weather.css
**CSS Updates**
- Implemented new CSS variables for improved styling and maintainability.
- Introduced complete dark and light themes for enhanced user experience.
- The application now intelligently uses the user's preferred color scheme via `prefers-color-scheme`.
**Next Steps:**
- A dark/light mode toggle will be implemented in a future change
> feat: dark and light themes implemented with new css variables

- src/App.css
- src/App.jsx
- src/components/LocationSearch.css
- src/components/ThemeToggle.css
- src/components/ThemeToggle.jsx
- src/components/UnitToggle.jsx
- src/context/ThemeContext.jsx
- src/index.css
- src/pages/Landing.css
- src/pages/Landing.jsx
- src/pages/Location.jsx
- src/pages/Weather.css
- src/pages/Weather.jsx
This PR introduces a theme toggle feature, allowing users to switch between light/dark themes, defaulting to their system preference.
- **Theme Context:** Manages theme state, provides toggleTheme, and defaults to system preference.
- **Theme Toggle Component:** Allows users to switch themes.
- **CSS Updates:** Uses data-theme attribute to apply light/dark styles, and applied minor fixes to previous PR to change the responsive design.
- Defaults to system theme.
- Users can toggle between themes.
- Theme preference is saved.
> feat: added dark and light toggle

- .vercelignore
- client/package-lock.json
- client/src/hooks/useWeather.js
- client/vite.config.js
- server/index.js
- vercel.json
This PR adds vercel.json to support full-stack deployment to Vercel.
- Builds the React frontend from `client/` using `@vercel/react`
- Deploys the Express backend from `server/index.js` via `@vercel/node`
- Routes `/api/*` requests to the backend and serves static files from the frontend
- Uses environment variables like `OPENWEATHER_API_KEY` via Vercel’s dashboard
- Supports local dev with Vite proxy and .env config
This enables seamless deployment of both frontend and backend on a single Vercel project.
> Configue for deployment with vercel

- vercel.json
> chore: configue for deployment with vercel

- .gitignore
- README.md
- api/getWeather.js
- src/hooks/useWeather.js
- vite.config.js
This pull request refactors the application to enhance the security of the OpenWeatherMap API key.
**Key Changes:**
- **Introduced a Vercel Serverless Function (`/api/getWeather`)**: This new function acts as an intermediary between the frontend and the OpenWeatherMap API. It securely retrieves weather data using the API key, which is now stored as an environment variable on Vercel and is not exposed to the client-side code.
- **Updated `useWeather.js` Hook**: The `useWeather` hook has been modified to call the `/api/getWeather` endpoint instead of directly interacting with the OpenWeatherMap API. It now receives the weather data (current and forecast) from the serverless function.
- **Configured Vite Proxy**: For local development, the Vite configuration (`vite.config.js`) has been …
> feat: getWeather vercel funtion ready for deployment

- src/pages/NotFound.css
- src/pages/NotFound.jsx
Improved the user experience of our 404 page by adding a dynamic rain effect with Javascript and CSS. This small enhancement aims to make encountering an error slightly less frustrating.
> feat: Make it Rain
